### PR TITLE
fix: ensure seaweedfs lifecycle policy is set correctly

### LINKED ISSUE #4028: Changing RETENTION_DAYS with nodestore
### Self-Hosted Version

25.10.0

### CPU Architecture

x86_64

### Docker Version

28.3.2

### Docker Compose Version

28.3.2

### Machine Specification

- [x] My system meets the minimum system requirements of Sentry

### Steps to Reproduce

1. Run `./install.sh`
2. Change `SENTRY_EVENT_RETENTION_DAYS` in `.env`
3. Re-run `./install.sh`

### Expected Result

The new `SENTRY_EVENT_RETENTION_DAYS` set in `.env` is used.

### Actual Result

AFAICT with the new `seaweedfs` container the lifecycle policy is only set during initial setup in `install/bootstrap-s3-nodestore.sh`

The setup for the lifecycle policy is behind this `if` 
https://github.com/getsentry/self-hosted/blob/976e06525ba2049fff8bd6c3a0bdc2853e36f2bf/install/bootstrap-s3-nodestore.sh#L10-L12

and the `else` branch is just a no-op

https://github.com/getsentry/self-hosted/blob/976e06525ba2049fff8bd6c3a0bdc2853e36f2bf/install/bootstrap-s3-nodestore.sh#L66-L89

This is probably a bit of an edge case, and some additional documentation about changing the retention period might be enough. I just noticed the issue while looking at the script, while manually upgrading to 25.10.0 after skipping the nodestore change for 25.9.0.

### Event ID

_No response_

### PR DESCRIPTION
**Pull request by kodebach**
Fixes #4028

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

File: install/bootstrap-s3-nodestore.sh [hunk 1]
```diff
@@ -62,7 +62,11 @@ if [[ $(echo "$bucket_list" | tail -1 | awk '{print $3}') != 's3://nodestore' ]]
 
   $dc exec seaweedfs mkdir -p /data/idx/
   $s3cmd --access_key=sentry --secret_key=sentry --no-ssl --region=us-east-1 --host=localhost:8333 --host-bucket='localhost:8333/%(bucket)' mb s3://nodestore
+else
+  echo "Node store already exists, skipping creation..."
+fi
 
+if [[ -z "${APPLY_AUTOMATIC_CONFIG_UPDATES:-}" || "$APPLY_AUTOMATIC_CONFIG_UPDATES" == 1 ]]; then
```
Comment (kodebach) [inline install/bootstrap-s3-nodestore.sh:69]: I added this if for users who manually changed their lifecycle policy, but this should probably be a separate CLI option or environment variable.

Ideally, we would check the existing policy matches what we expect or explicitly just update the `<Days>` part in our `<Rule>`. But that would require parsing XML and I don't think there is currently a setup to do this

Comment (aldy505) [reply install/bootstrap-s3-nodestore.sh:69]: > Ideally, we would check the existing policy matches what we expect or explicitly just update the `<Days>` part in our `<Rule>`. But that would require parsing XML and I don't think there is currently a setup to do this

Yeah I don't think that's possible

Comment (BYK) [reply install/bootstrap-s3-nodestore.sh:69]: There's this tool: https://github.com/TomWright/dasel

**Comment by aldy505** [comment]
why did I approve it again...

**Comment by aldy505** [comment]
I'm gonna merge this.
