### PR TITLE
Use docker compose exec to create additional kafka topics

### LINKED ISSUE #2754: "Creating additional Kafka topics" step is failed
### Self-Hosted Version

24.1.0

### CPU Architecture

x86_64

### Docker Version

25.0.1

### Docker Compose Version

2.18.1

### Steps to Reproduce

after the disk is full launching install.sh gives an error at the step **Creating additional Kafka topics**
Clearing all docker caches and containers doesn't help. Kafka and zookeeper volumes were also deleted before launch

### Expected Result

correctly working self-hosted sentry

### Actual Result

```
▶ Creating additional Kafka topics ...
Error in install/create-kafka-topics.sh:5.
'EXISTING_KAFKA_TOPICS=$($dcr -T kafka kafka-topics --list --bootstrap-server kafka:9092 2>/dev/null)' exited with status 1
-> ./install.sh:main:32
--> install/create-kafka-topics.sh:source:5
```

### Event ID

_No response_

exec:
`docker-compose run --rm kafka kafka-topics --list --bootstrap-server kafka:9092`
output:
`[2024-01-31 14:06:17,120] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.25.0.4:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)`

no changes were made to the compose file
When running kafka in the background, no critical errors were noticed in the logs. port 9092 listens on docker network address

### LINKED ISSUE #2903: "Creating additional Kafka topics" step is failing
### Self-Hosted Version

24.3.0

### CPU Architecture

x86_64

### Docker Version

25.0.4

### Docker Compose Version

2.19.0

### Steps to Reproduce

There's another, locked issue, see https://github.com/getsentry/self-hosted/issues/2754

Running `install.sh` is failing for me. It looks like, it's related to the usage of `docker compose run`, as this will create a new container. By using `docker compose exec`, it worked for me.

### Expected Result

correctly working self-hosted sentry

### Actual Result

Running containers:
```
CONTAINER ID   IMAGE                                      COMMAND                  CREATED          STATUS                                     PORTS                          NAMES
6a5218233205   confluentinc/cp-kafka:5.5.7                "kafka-topics --list…"   1 second ago     Up Less than a second (health: starting)   9092/tcp                       sentry-kafka-run-e7550f2c77d2
7cb7fab008c3   confluentinc/cp-kafka:5.5.7                "/etc/confluent/dock…"   54 seconds ago   Up 23 seconds (healthy)                    9092/tcp                       sentry-kafka-1
36c9a085aa91   redis:6.2.13-alpine                        "docker-entrypoint.s…"   54 seconds ago   Up 54 seconds (healthy)                    6379/tcp                       sentry-redis-1
75e41d676dc8   confluentinc/cp-zookeeper:5.5.7            "/etc/confluent/dock…"   54 seconds ago   Up 53 seconds (healthy)                    2181/tcp, 2888/tcp, 3888/tcp   sentry-zookeeper-1
d8866d7221f6   clickhouse-self-hosted-local               "/entrypoint.sh"         54 seconds ago   Up 53 seconds (healthy)                    8123/tcp, 9000/tcp, 9009/tcp   sentry-clickhouse-1
```

sentry-kafka-run-e7550f2c77d2 logs:
```
root@sentry1:/srv/sentry# docker logs sentry-kafka-run-e7550f2c77d2
[2024-03-19 07:33:03,626] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.26.0.6:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-03-19 07:33:03,729] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.26.0.6:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-03-19 07:33:03,829] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.26.0.6:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-03-19 07:33:04,131] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.26.0.6:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-03-19 07:33:04,632] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.26.0.6:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-03-19 07:33:05,535] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.26.0.6:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-03-19 07:33:06,738] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.26.0.6:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-03-19 07:33:07,740] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.26.0.6:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-03-19 07:33:08,943] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.26.0.6:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
```

The ip address shown in the log is the one of the `run` container, not `sentry-kafka-1`. It looks like, as if it's trying to connect to itself and that's why it's failing.

```
root@sentry1:/srv/sentry# docker compose run --rm -T kafka kafka-topics --list --bootstrap-server kafka:9092
[+] Creating 1/0
 ✔ Container sentry-zookeeper-1  Running                                                                0.0s
[2024-03-19 07:43:53,412] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.26.0.54:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-03-19 07:43:53,514] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.26.0.54:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-03-19 07:43:53,715] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.26.0.54:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-03-19 07:43:53,917] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.26.0.54:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-03-19 07:43:54,418] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.26.0.54:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-03-19 07:43:55,222] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.26.0.54:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-03-19 07:43:56,325] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.26.0.54:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-03-19 07:43:57,428] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.26.0.54:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-03-19 07:43:58,531] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.26.0.54:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-03-19 07:43:59,634] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.26.0.54:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-03-19 07:44:00,737] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.26.0.54:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-03-19 07:44:01,840] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka/172.26.0.54:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
```

And here with `docker compose exec`:
```
root@sentry1:/srv/sentry# docker compose exec -T kafka kafka-topics --list --bootstrap-server kafka:9092
__consumer_offsets
cdc
event-replacements
event-replacements-legacy
events
events-subscription-results
generic-events
generic-metrics-distributions-subscription-results
generic-metrics-sets-subscription-results
generic-metrics-subscription-results
group-attributes
ingest-attachments
ingest-events
ingest-metrics
ingest-monitors
ingest-occurrences
ingest-performance-metrics
ingest-replay-events
ingest-replay-recordings
ingest-sessions
ingest-transactions
metrics-subscription-results
outcomes
outcomes-billing
processed-profiles
profiles
profiles-call-tree
scheduled-subscriptions-events
scheduled-subscriptions-generic-metrics-counters
scheduled-subscriptions-generic-metrics-distributions
scheduled-subscriptions-generic-metrics-sets
scheduled-subscriptions-metrics
scheduled-subscriptions-sessions
scheduled-subscriptions-transactions
sessions-subscription-results
shared-resources-usage
snuba-attribution
snuba-commit-log
snuba-dead-letter-generic-events
snuba-dead-letter-generic-metrics
snuba-dead-letter-group-attributes
snuba-dead-letter-inserts
snuba-dead-letter-metrics
snuba-dead-letter-metrics-counters
snuba-dead-letter-metrics-distributions
snuba-dead-letter-metrics-sets
snuba-dead-letter-querylog
snuba-dead-letter-replays
snuba-dead-letter-sessions
snuba-generic-events-commit-log
snuba-generic-metrics
snuba-generic-metrics-counters-commit-log
snuba-generic-metrics-distributions-commit-log
snuba-generic-metrics-sets-commit-log
snuba-metrics
snuba-metrics-commit-log
snuba-metrics-summaries
snuba-queries
snuba-replay-events
snuba-sessions-commit-log
snuba-spans
snuba-transactions-commit-log
transactions
transactions-subscription-results
root@sentry1:/srv/sentry#
```

### Event ID

_No response_

### PR DESCRIPTION
**Pull request by saz**
fixes #2903
fixes #2754

`docker compose run` will start a second kafka container, instead of reusing the existing one. 
`install/create-kafka-topics.sh` is failing, as `kafka-topics` is trying to connect within the same container.

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Review by aldy505 — APPROVED** [review]

**Comment by BYK** [comment]
I think you need a `docker compose up kafka` before everything so you have a container instance to exec in?

**Comment by BYK** [comment]
Lol, I'm pretty sure I'm the one who left that note and looks like it is not very effective 😅 Also, this was pre Compose 2.0 time where we did not have the `--wait` option. I think adding the following as preamble would be a no-op if `kafka` is already running as the note suggests:

```shell
$dc up --no-build --no-recreate --wait kafka
```

**Comment by BYK** [comment]
Btw the previous script just does `$dcr snuba` which implies getting `kafka` up and in healthy state as it's a dependency of `snuba`. Quite implicit.

**Review by hubertdeng123 — APPROVED** [review]

**Comment by hubertdeng123** [comment]
@BYK Think you're right, CI will fail as kafka isn't up yet. Let's see what happens

**Comment by aldy505** [comment]
CI didn't fail

**Comment by hubertdeng123** [comment]
Ok, running snuba-api will bring up zookeeper, redis, clickhouse, and kafka

**Comment by aldy505** [comment]
@saz can you add a line before executing everything else on the setup-kafka-topics as suggested by Burak here: https://github.com/getsentry/self-hosted/pull/2904#issuecomment-2007024937

That should be all

**Comment by saz** [comment]
@aldy505 Done. I've also removed the comment

**Comment by hubertdeng123** [comment]
Looks like we cannot use `--wait` yet since it's not available in v2.0.1

**Comment by saz** [comment]
Any other things I can do to solve this issue? Sticking to the implicit way isn't an option? I've seen a different issue upgrading `docker compose`, which will make it possible to solve this in the future.

**Comment by azaslavsky** [comment]
> Any other things I can do to solve this issue? Sticking to the implicit way isn't an option? I've seen a different issue upgrading `docker compose`, which will make it possible to solve this in the future.

Is the issue with `self-hosted`, or is this some other unrelated problem that prevents a `docker compose` update?

**Comment by saz** [comment]
@azaslavsky it's about adding `$dc up` as suggested in https://github.com/getsentry/self-hosted/pull/2904#issuecomment-2007024937 with this PR, but `--wait` isn't supported in docker compose 2.0.1

**Comment by aldy505** [comment]
We could just remove the `--wait`, and put up a script after that `$dc up` command to periodically check whether it's healthy yet.

```bash
while [ true ]
do
    $kafka_healthy=$(docker compose ps kafka | grep 'healthy')
    if [ ! -z "$kafka_healthy" ]; then
      break
    fi

    echo "Kafka container is not healthy, waiting for 30 seconds. If this took too long, abort the installation process, and check your Kafka configuration"
    sleep 30s
done
```

One alternative would be using the [wait-for-it](https://github.com/vishnubob/wait-for-it/blob/master/wait-for-it.sh) script.

**Comment by saz** [comment]
@aldy505 Changed as requested

File: install/create-kafka-topics.sh [hunk 1]
```diff
@@ -1,12 +1,24 @@
 echo "${_group}Creating additional Kafka topics ..."
 
-# NOTE: This step relies on `kafka` being available from the previous `snuba-api bootstrap` step
+$dc up --no-build --no-recreate kafka
+
+while [ true ]
+do
+    $kafka_healthy=$(docker compose ps kafka | grep 'healthy')
```
Comment (aldy505) [inline install/create-kafka-topics.sh:7]: Ah sorry, this should be `$dc ps kafka`

```suggestion
    $kafka_healthy=$($dc ps kafka | grep 'healthy')
```

**Comment by saz** [comment]
@aldy505 Changed. Thanks for spotting it!

**Comment by aldy505** [comment]
Gentle ping @hubertdeng123 @BYK

**Review by BYK — APPROVED** [review]
LGTM, thanks! :)

File: install/create-kafka-topics.sh [hunk 2]
```diff
@@ -1,12 +1,24 @@
...
+while [ true ]
+do
+    $kafka_healthy=$($dc ps kafka | grep 'healthy')
+    if [ ! -z "$kafka_healthy" ]; then
+      break
+    fi
+
+    echo "Kafka container is not healthy, waiting for 30 seconds. If this took too long, abort the installation process, and check your Kafka configuration"
+    sleep 30s
+done
```
Comment (BYK) [inline install/create-kafka-topics.sh:14]: Protip, you can do something like this: https://github.com/getsentry/self-hosted/blob/7143d887430ebfa624df75d18448a49df6c908c5/_integration-test/run.sh#L47

```suggestion
echo "Waiting for kafka container to be healthy for up to 30 seconds."
timeout 30 bash -c 'until $($dc ps kafka | grep -q 'healthy'); do printf '.'; sleep 0.5; done'
```

Comment (BYK) [reply install/create-kafka-topics.sh:14]: Well, then let's make it 300s? :D

**Comment by webliving** [comment]
Self-Hosted Version
24.3.0

CPU Architecture
x86_64

Docker Version
26.0.0

Docker Compose Version
1.27.1

Centos Version
7.9

.install.sh error
 
```
dependency failed to start: container sentry-self-hosted-kafka-1 is unhealthy
Error in install/bootstrap-snuba.sh:3.
'$dcr snuba-api bootstrap --no-migrate --force' exited with status 1
-> ./install.sh:main:32
--> install/bootstrap-snuba.sh:source:3

Cleaning up...
```

File: install/create-kafka-topics.sh (hunk 2 above)
Comment (saz) [reply install/create-kafka-topics.sh:14]: So... Applying the change with at least 300s? Maybe it's better to even raise it a bit further, just in case?

Comment (aldy505) [reply install/create-kafka-topics.sh:14]: To be honest, I'm not 100% sure. I don't use Kafka anymore on my Sentry instance, but for a minimum 4 core CPU, Kafka is rather problematic to boot up. I think it's okay to stay as it is (rather than changing to Burak's recommendation).

Comment (saz) [reply install/create-kafka-topics.sh:14]: @BYK What's your opinionen? Would be nice to get this merged

Comment (aldy505) [reply install/create-kafka-topics.sh:14]: Okay let's settle this at 150s :laughing:

**Comment by aldy505** [comment]
Hey @azaslavsky @hubertdeng123 can we merge this before tomorrow's release?

**Comment by azaslavsky** [comment]
It looks like the tests are failing - can y'all see the action output? Ex: https://github.com/getsentry/self-hosted/actions/runs/8695624967/job/23847053353?pr=2904

File: install/create-kafka-topics.sh (hunk 2 above)
Comment (hubertdeng123) [reply install/create-kafka-topics.sh:14]: I think the reason CI is failing is because you may need to remove the $ in front of $kafka_healthy

Comment (aldy505) [reply install/create-kafka-topics.sh:14]: @hubertdeng123 can you just directly commit it?

**Comment by azaslavsky** [comment]
Looks like it is still failing :(

**Comment by saz** [comment]
@azaslavsky I don't understand, why it's not able to attach to the container. I'm not able to reproduce this on my system :(

**Comment by saz** [comment]
I've found the issue. Would be great, if someone can approve the workflows again

**Comment by azaslavsky** [comment]
🤞
